export const NE = 'NE'
export const SW = 'SW'
export const SE = 'SE'
export const NW = 'NW'
//export const ROW_SPLIT = 'ROW_SPLIT'
//export const COL_SPLIT = 'COL_SPLIT'

export const ROW = 'ROW'
export const COL = 'COL'
export const JOIN = 'JOIN'
export const SPLIT = 'SPLIT'

export const CHILD_ABOVE = 'CHILD_ABOVE'
export const CHILD_BELOW = 'CHILD_BELOW'
export const CHILD_LEFT = 'CHILD_LEFT'
export const CHILD_RIGHT = 'CHILD_RIGHT'
export const CHILD_NONE = 'CHILD_NONE'

export const SET_STATE = 'SET_STATE'

export const CORNER_DOWN = 'CORNER_DOWN'

export const ADD_CHILD_PANE = 'ADD_CHILD_PANE'
export const REMOVE_CHILD_PANE = 'REMOVE_CHILD_PANE'
export const REMOVE_PARENT_PANE = 'REMOVE_PARENT_PANE'
export const SET_SPLIT_RATIO = 'SET_SPLIT_RATIO'
export const SET_SIZE = 'SET_SIZE'
export const SET_BLOCK = 'SET_BLOCK'
export const SET_DIVIDER_DOWN = 'SET_DIVIDER_DOWN'
export const SET_CORNER_DOWN = 'SET_CORNER_DOWN'
export const SET_PANE_PROPS = 'SET_PANE_PROPS'
export const SET_CORNER_HOVER = 'SET_CORNER_HOVER'

export const JOIN_RIGHT_ARROW = 'JOIN_RIGHT_ARROW'
export const JOIN_UP_ARROW = 'JOIN_UP_ARROW'
export const JOIN_LEFT_ARROW = 'JOIN_LEFT_ARROW'
export const JOIN_DOWN_ARROW = 'JOIN_DOWN_ARROW'
